### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by sandervankasteel** [devinhalladay/spotio#12]
I wanna see if this is possible, I don't think it is impossible but it all depends if Spotify does any obfuscation on their binaries files and how the internal structure is setup of the Android application.

**Comment by KamranMackey** [comment]
I would think that the Spotify app would use the same type of skinning system, all the apps are in one single cross-platform base.

**Comment by devinhalladay** [comment]
I don't see why it wouldn't be possible but I don't know anything about Android so this one's all on you guys if you want to see it come to fruition. I know Windows + Mac (and possibly Linux?) use the same skinning system, but I've yet to dig into iOS to see if it uses a similar system. If it does use CSS to style things then we'd have to rewrite the skin for iOS and Android specifically since there's no mobile-specific code in the desktop app's skin, which could be a huge undertaking (especially on Android)

**Comment by sandervankasteel** [comment]
Regards to Android support, I just had a quick peek in the APK file for Android. Spotify builds the UI using the standard Android XML layout but the main problem is that is in a binary form (see screenshot below), so before we can even think about skinning the Android client. We need to find a Android de-compiler, that has support for decompiling Android XML layout files. 

![screen shot 2016-08-25 at 08 42 30](https://cloud.githubusercontent.com/assets/17492906/17959376/43e6b6ae-6aa0-11e6-86d1-d8ca4ec7b124.png)
![screen shot 2016-08-25 at 08 38 27](https://cloud.githubusercontent.com/assets/17492906/17959377/43ec9b32-6aa0-11e6-9275-64951bce33c1.png)

Offtopic: Yes Linux does the use the same skinning system as Mac and Windows.

**Comment by devinhalladay** [comment]
Thanks for the thorough research (and for confirming that Linux does indeed use the standard skinning platform).

It seems to me that Android will likely have to wait a while, as I don't know enough about Android development to coordinate an effort to skin the app. If you'd like to take this on as well at some point in the future I'd do what I can to get you the resources you need to get it working, but seeing as we're all likely busy people I think it's best to push the milestone on this off to a more future-distant release. Thoughts?

**Comment by sandervankasteel** [comment]
Agreed, push it to the future. I will pick this port up once the Linux port is completed and I've had some to properly research Android decompilers. Unless anybody else wants to do it ?

**Comment by abarisain** [comment]
>We need to find a Android de-compiler, that has support for decompiling Android XML layout files.

There are not many who do that well for recent android versions. Best in class is currently apktool, which will easily allow you to do what I want. Some people have made even bigger modifications: http://forum.xda-developers.com/showthread.php?t=2612319

That said, that's hoping spotify doesn't remotely inject views using java code, because that's gonna be really hard to patch

**Comment by sandervankasteel** [comment]
Thanks @abarisain I will have a look soon :)

**Comment by devinhalladay** [comment]
Closing this issue for now because logistically this is impossible without some more dedicated resources
