### ISSUE TITLE
Spotio quits shortly after opening and is replaced with regular Spotify 

### ISSUE THREAD

**Issue by WillDimarco** [devinhalladay/spotio#30]
@devinhalladay

  @sandervankasteel Hey (fe)ma(le)n(s). 

Love all the work you've done, it looks amazing, and I am super glad it's out in the open. But I have been having a major problem, I downloaded the app a few minutes ago. And although i have set my mac to automatically accept opening applications from foreign places, my computer still asked, but it opened anyways, so i thought that was fine. Anyway, I deleted my old Spotify and opened up the new one. It got interesting when Spotio launched, everything _looked_ fine, but my albums weren't showing up and there was a considerable amount of lag (although that lag may be normal). On top of this, the app would close after a couple seconds of opening, immediately replaced by the old Spotify. It didn't matter how many times i tried, Spotio would just crash, (also seemed to change the app icon when i moved it to my desktop). Spotio played music fine and looked awesome, with the exception of the lag (maybe) and the missing albums. I was just wondering if you have a solution or feedback to all or any of my issues here?

[spotio issue.mp4.zip](https://github.com/devinhalladay/spotio/files/649004/spotio.issue.mp4.zip)

ZIP file containing mp4 video of my issue 

Much Love 

Wilco

**Comment by sandervankasteel** [comment]
Hi @WillDimarco,

The flashing that you are experiencing isn't weird to see. That's because of Spotio and how it's white background is applied.

But the main issue you are having, is that Spotio is replaced with a new version of Spotify. That's because of the internal updater of Spotify. In the past Spotify would only update the components it used but nowadays after an update is found, (on OS X / MacOS!) Spotify will replace it's whole application (and therefor, remove any modifications done by Spotio) by a new version of Spotify and restart the application. The only way to currently "fix" this, is to patch your own version of Spotify and sign it yourself on OS X / MacOS (see #23 for resigning your own application and see the README for building your own version of Spotify)

I hope to have some decent time at the end of the year, to finish up my external patcher application. So it's just a matter of "patching" up the Spotify application and Spotify should be white again.

**Comment by WillDimarco** [comment]
Thank you so much! I will definitely look into those other issues to fix my own. Thanks again!

Wilco

**Comment by sandervankasteel** [comment]
No problem :+1: 

@devinhalladay can you close this issue ?

**Comment by WillDimarco** [comment]
i don't know how haha

**Comment by devinhalladay** [comment]
Hey guys, thanks for working through this! @WillDimarco I apologize for all these issues; I released Spotio right as school started back up so I lost the opportunity to keep updating Spotio and the time to work on an updater application to patch files after Spotify issues an update. Hopefully this will come sooner or later (but, in the meantime, you may want to check out Pandora's new streaming service coming out in Q1 next year!! I have a friend working there and he's so excited for the release, plus their design is really great and feels like a second home after Rdio).

@sandervankasteel Thanks so so much for your help and upkeep in the issues here; I haven't even had the time to open Github for a few weeks so I appreciate it very much. If you're working on that updater/patcher application and need help, let me know and I'd be happy to lend a hand this month during my winter break from school! If not, I'm hoping I'll find some time to at least start it in the upcoming month or two.

Closing this issue now but feel free to keep discussion going afterward!

**Comment by sandervankasteel** [comment]
@devinhalladay No problem 👍  I wanna be able to have a minimal MVP code for the patcher done when my winter break from school is done. At first I think it will only support OS X, but that should give us at least a baseline on where Spotify is heading towards regarding updating and how we should structure our patcher application. So we could eventually set it up so it's multiplatform.
