### ISSUE TITLE
.

### ISSUE THREAD

**Issue by IcarusKai** [devinhalladay/spotio#35]

**Comment by devinhalladay** [comment]
@IcarusKai awesome, thank you! I'd appreciate it that if you create this in a separate repo, make that repo a fork from this one so when you're finished I can merge the windows version into the repo.

The goal with this project is to have a unified build system that can distribute the styling files directly into a .exe, .app, as well as a .deb or whatever Linux distros might need, so that we only have to make the changes to stylesheets once and our streaming build system will automatically rebuild each OS's app.

If you can keep this in mind while porting to Windows, that would be great—at the very least it would save me a ton of work this summer when I pick Spotio back up and roll it into a unified customizable theming system for Spotify.
