### ISSUE TITLE
Windows Version?

### ISSUE THREAD

**Issue by BitesizedLion** [devinhalladay/spotio#42]
Is a Windows Version possible?

**Comment by jnylen** [comment]
@BitesizedLion,
This isn't really developed at all anymore.

**Comment by devinhalladay** [comment]
Yeah, sorry @BitesizedLion @jnylen, I haven't had any time since release to fix the release after Spotify broke my theme development workflow, so I haven't even thought about the windows version. However, theoretically, the Windows version still works the same. I looked into it at one point, and Spotify stores the theme files in a system directory somewhere as HTML, JS, and CSS. If you can find those files (I don't have time to look right now), you should be able to port this yourself if you'd like to contribute.

Closing as wontfix but feel free to continue commenting or open a PR!!
