### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by evelynharthbrooke** [devinhalladay/spotio#7]
Is there any way that this can be ported to Windows? Would love to try this theme out but I have a Windows machine.

**Comment by devinhalladay** [comment]
Ideally it should be coming this weekend! I’m going to start working on it
tomorrow :) I don’t want to leave anyone hanging! Linux support will
hopefully be coming as well.

On August 22, 2016 at 9:32:25 PM, Kamran Mackey (notifications@github.com)
wrote:

Is there anyway that this can be ported to Windows? Would love to try this
theme out but I have a Windows machine.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/devinhalladay/spotio/issues/7>, or mute the thread

**Comment by KamranMackey** [comment]
Awesome! I can't wait! +1 :smile:

**Comment by UdoKifferbrehl** [comment]
Awesome 😀

**Comment by devinhalladay** [comment]
It might be a few days later than expected because I'm dealing with a lot right now, but if anyone else wants to take the reigns on this until I'm back and ready to continue development, please feel free to submit a PR. It should be a simple porting process, and then all you need to do is add a task  or two to the `gruntfile` and we should be good to go

**Comment by devinhalladay** [comment]
Would someone with a Windows machine take the lead on this? All you should need to do is unzip the .exe, study the structure a bit, then write a grunt task to inject out asset files back into the .exe. I would do it but I'm back on campus now and the wifi is pretty bad so my windows VM isn't downloading

**Comment by prediscover** [comment]
:( unfortunately I do not know how to do what you mentioned, otherwise i would!!

**Comment by KamranMackey** [comment]
@devinhalladay Spotify on Windows doesn't have the assets embedded into the application. They have the assets in their own separate folder under %AppData%/Roaming/Spotify/Apps. Screenshot is below:

![Spotify Assets](https://cloud.githubusercontent.com/assets/1617100/18025961/50c53bc8-6bf6-11e6-9e60-aeac230de628.png)

**Comment by devinhalladay** [comment]
Thank you so much for the research! Would you be willing to write a grunt copy command for Windows? If not I can likely do it tonight but I'll need help with testing since I can't get my VM downloaded

**Comment by devinhalladay** [comment]
Oh no!! I just realized we need to create an installer for Windows if the Asset files are not stored within the app...how can we do this? I *definitely* need help on this one. Maybe use electron to build a little helper app that runs a grunt task in the background and copies over the files??

**Comment by devinhalladay** [comment]
@ColeTownsend do you happen to know if I can use electron to do what I mentioned above ^^? That might actually be all we need to solve the issues with updating the app to match spotify's update cycle anyways

**Comment by KamranMackey** [comment]
@devinhalladay Electron is a really extensible framework, I think it would be possible.

**Comment by Dafnik** [comment]
I could program an "installer" in C# which can also download files etc.

**Comment by devinhalladay** [comment]
C# would be good for Windows but I think building a single cross platform installer would be most beneficial so maybe electron is the best route and we can package reusable code in all three app formats (exe, app, deb)

**Comment by KamranMackey** [comment]
@devinhalladay Yeah. But when will Windows support be done?

**Comment by Pival81** [comment]
it should be easy, just create an installer using winrar.

**Comment by devinhalladay** [comment]
We need cross-platform installer and updater before we can bring support to a new platform. Otherwise we're just further segmenting the spotio codebase in a bad way and essentially releasing bad software.If you'd like to contribute, the plan is to use electron

**Comment by Pival81** [comment]
I don't think we can create a cross-platform installer, because linux needs packages (and there are at least three kind of packages: deb, rpm, pkg.tar, depending on the distribution), macos needs .app, and windows stores the files you have to edit in the AppData folder.
So i think our best bet is to have multiple maintainers for all kind of installer.

**Comment by devinhalladay** [comment]
Cross-platform is entirely doable because we're not installing an app, we're just replacing the files inside the Spotify app. All we need to do is identify which OS the user is on, then run the code to replace the files in that system's specific asset file location, and then we're done. Same with the updater. I'm not worried about linux because we have a script already to install it there, and that will remain the same because linux is too fragmented as-is; but Windows and macOS both use the same file structure, albeit in different locations, so a cross-platform(windows and os x) installer is the best solution. Using Electron is also the best solution for that, most likely, because we can program the installers in the same codebase and then export them to .exe and .app really easily

**Comment by devinhalladay** [comment]
I'm looking to minimize the amount of work we have to do in the longrun because I am far too busy to continue maintaining Spotio on my own, let alone making sure three separate codebases follow the same standards

**Comment by devinhalladay** [comment]
Again, we're not *actually* installing any app as of now; we're just running scripts to replace `App` files with the Spotio version.

**Comment by devinhalladay** [comment]
However, for the time being, if you'd like to make an MVP for the Windows version of the installer (and updater; they need to come as a package and the installer will also install and update helper that blocks spotify updates from coming through and instead checks for updates from our github releases), then feel free and I'll check it out. If it looks good and you're willing to maintain it, that'll be fine with me

**Comment by Jhonmark24** [comment]
please aplication ,thanks

**Comment by devinhalladay** [comment]
Hey guys, it doesn't look like Windows support will be coming any time soon. I will hopefully be updating the Mac app in the next few weeks to work better with the latest Spotify design updates, but beyond that I'm not sure how much time I will be able to commit to Spotio until the summer. I'm not giving up on the project but I just don't have the time or energy to commit to it right now. I will send out an update to newsletter subscribers in a couple weeks with updates, so stay tuned.

**Comment by GeroldSetz** [comment]
Hi Devin, 
any news on Windows support?

Best, Gerold

**Comment by devinhalladay** [comment]
@GeroldSetz nope, I do not have the time to keep maintaining this project, and beyond the milestone of establishing Windows support, we would need to redo most of the code for Spotio because Spotify has changed their system so much.

Feel free to submit a pull request if you want to take a stab at either of these things.
